# Generated by Django 4.1.2 on 2022-11-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='max_partcipants',
            new_name='max_participants',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
