# Generated by Django 4.1.1 on 2022-12-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=True, verbose_name='Aprovado'),
        ),
    ]
