# Generated by Django 4.1.3 on 2022-12-01 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_promotor_profile_photo'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='promotor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.promotor'),
        ),
    ]
