# Generated by Django 4.1.1 on 2022-10-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.event')),
                ('service', models.CharField(blank=True, max_length=255)),
                ('has_flat_price', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
