# Generated by Django 4.1.2 on 2022-12-01 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_event_id_alter_event_promotor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='favorito',
            field=models.ManyToManyField(blank=True, related_name='favorito', to=settings.AUTH_USER_MODEL),
        ),
    ]
