# Generated by Django 4.1.3 on 2022-12-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_approved'),
        ('events', '0003_event_approved'),
    ]

    operations = [
    ]
