# Generated by Django 4.1.3 on 2022-11-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_promotor_confirmado_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotor',
            old_name='confirmado',
            new_name='approved',
        ),
        migrations.AddField(
            model_name='promotor',
            name='request_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
