# Generated by Django 4.1.3 on 2022-11-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_confirmado_promotor_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
